[package]
name = "nvim_calc_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
log = "0.4.22"
neovim-lib = "0.6.1"
rmpv = { version ="0.4", features=["with-serde"] }
simplelog = "0.12.2"
